# Generated by Django 3.0.6 on 2020-05-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200508_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.CharField(default=500, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.CharField(default='500', max_length=5),
            preserve_default=False,
        ),
    ]
