# Generated by Django 3.0.6 on 2020-05-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
